import React, { useState } from 'react';
import { MedicalDocument } from '../../types';
import { HelpCircle, CheckSquare, Square, Copy, Check, Printer, FileText, ArrowRight } from 'lucide-react';

interface DoctorQuestionsHubProps {
  documents: MedicalDocument[];
  onSelectDocument: (doc: MedicalDocument) => void;
}

export const DoctorQuestionsHub: React.FC<DoctorQuestionsHubProps> = ({
  documents,
  onSelectDocument,
}) => {
  // Aggregate suggested questions across all documents
  const allQuestions: {
    id: string;
    question: string;
    doc: MedicalDocument;
    category: string;
  }[] = [];

  documents.forEach((doc) => {
    doc.suggestedQuestions.forEach((q, idx) => {
      allQuestions.push({
        id: `${doc.id}-q-${idx}`,
        question: q,
        doc,
        category: doc.type === 'prescription' ? 'Prescription Clarification' : doc.type === 'lab_report' ? 'Lab Follow-up' : 'Post-discharge Care',
      });
    });

    // Also include questions from flagged interaction alerts
    doc.interactions.forEach((int) => {
      if (int.doctorQuestionPrompt) {
        allQuestions.push({
          id: `${doc.id}-int-${int.id}`,
          question: int.doctorQuestionPrompt,
          doc,
          category: 'Drug Interaction & Safety',
        });
      }
    });
  });

  const [checkedQuestions, setCheckedQuestions] = useState<Record<string, boolean>>({});
  const [copied, setCopied] = useState<boolean>(false);

  const toggleQuestion = (id: string) => {
    setCheckedQuestions((prev) => ({
      ...prev,
      [id]: !prev[id],
    }));
  };

  const handleCopyAll = () => {
    const textList = allQuestions.map((q, i) => `${i + 1}. ${q.question} (Source: ${q.doc.title})`).join('\n\n');
    navigator.clipboard.writeText(`Questions for My Doctor / Pharmacist (Generated by Medora AI):\n\n${textList}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div id="medora-doctor-questions-hub" className="bg-[#120d28]/90 backdrop-blur-xs rounded-2xl border border-[#2d2259] p-5 sm:p-7 shadow-xl shadow-purple-950/20 space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-[#261d4a]">
        <div>
          <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-linear-to-r from-purple-950 to-pink-950 border border-purple-800/50 text-[#c084fc] text-xs font-bold font-mono mb-1">
            <HelpCircle className="w-3.5 h-3.5" />
            <span>APPOINTMENT AGENDAS</span>
          </div>
          <h3 className="text-xl font-extrabold text-white font-display">
            Smart Questions for Your Next Doctor or Pharmacist Visit
          </h3>
          <p className="text-xs sm:text-sm text-neutral-400">
            Synthesized directly from your lab deviations, handwriting uncertainties, and medication instructions.
          </p>
        </div>

        <div className="flex items-center gap-2 self-start sm:self-auto">
          <button
            onClick={handleCopyAll}
            className="px-3 py-1.5 rounded-xl border border-[#2d2259] bg-[#181135] hover:bg-[#22174c] text-purple-200 text-xs font-bold flex items-center gap-1.5 transition-colors cursor-pointer min-h-[38px]"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-[#c084fc]" />}
            <span>{copied ? 'Copied' : 'Copy All'}</span>
          </button>
          <button
            onClick={handlePrint}
            className="px-3 py-1.5 rounded-xl bg-linear-to-r from-[#8b5cf6] to-[#ec4899] hover:from-[#7c3aed] hover:to-[#db2777] text-white text-xs font-bold flex items-center gap-1.5 transition-colors cursor-pointer min-h-[38px] shadow-md shadow-purple-950/40"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Sheet</span>
          </button>
        </div>
      </div>

      {/* Questions Checklist */}
      {allQuestions.length > 0 ? (
        <div className="space-y-3">
          {allQuestions.map((qItem) => {
            const isChecked = Boolean(checkedQuestions[qItem.id]);

            return (
              <div
                key={qItem.id}
                onClick={() => toggleQuestion(qItem.id)}
                className={`p-4 rounded-xl border transition-all cursor-pointer flex items-start gap-3.5 ${
                  isChecked
                    ? 'bg-emerald-950/30 border-emerald-500/40 opacity-70'
                    : 'bg-[#160f33] border-[#2d2259] hover:bg-[#1a123d] hover:border-[#8b5cf6]/60 shadow-xs'
                }`}
              >
                <div className="pt-0.5 text-neutral-400">
                  {isChecked ? (
                    <CheckSquare className="w-5 h-5 text-emerald-400" />
                  ) : (
                    <Square className="w-5 h-5 text-purple-400 hover:text-purple-300" />
                  )}
                </div>

                <div className="flex-1 space-y-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-[#241a4a] text-purple-200 border border-purple-800/40 font-mono uppercase">
                      {qItem.category}
                    </span>
                    <span className="text-[11px] text-neutral-400 font-mono">
                      From: {qItem.doc.title.split('&')[0]}
                    </span>
                  </div>

                  <p className={`text-xs sm:text-sm font-semibold leading-relaxed ${isChecked ? 'line-through text-neutral-500' : 'text-neutral-200'}`}>
                    {qItem.question}
                  </p>
                </div>

                <button
                  onClick={(e) => {
                    e.stopPropagation();
                    onSelectDocument(qItem.doc);
                  }}
                  className="text-xs text-[#c084fc] font-bold hover:underline shrink-0 flex items-center gap-1 self-center cursor-pointer"
                >
                  Inspect <ArrowRight className="w-3 h-3" />
                </button>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="py-8 text-center text-xs text-neutral-500 font-mono">
          No questions generated yet. Upload a document to generate personalized appointment talking points.
        </div>
      )}
    </div>
  );
};
